--------------------------------------------------------
-- Archivo creado  - domingo-diciembre-10-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ALQUILERES
--------------------------------------------------------

  CREATE TABLE "ISIS2304C211720"."ALQUILERES" 
   (	"ID" NUMBER, 
	"VIDEO_ID" NUMBER, 
	"USER_NAME" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "ISIS2304C211720"."CLIENTES" 
   (	"ID" NUMBER, 
	"NOMBRE_USUARIO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table EQUIVALENCIAS
--------------------------------------------------------

  CREATE TABLE "ISIS2304C211720"."EQUIVALENCIAS" 
   (	"NOMBRE1" VARCHAR2(50 BYTE), 
	"NOMBRE2" VARCHAR2(50 BYTE), 
	"TIPO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table INGREDIENTES
--------------------------------------------------------

  CREATE TABLE "ISIS2304C211720"."INGREDIENTES" 
   (	"NOMBRE" VARCHAR2(20 BYTE), 
	"DESCRIPCION" VARCHAR2(50 BYTE), 
	"TRADUCCION" VARCHAR2(50 BYTE), 
	"CANTIDAD" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table MENU_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "ISIS2304C211720"."MENU_PRODUCTO" 
   (	"NOMBRE_MENU" VARCHAR2(20 BYTE), 
	"NOMBRE_PRODUCTO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table MENUS
--------------------------------------------------------

  CREATE TABLE "ISIS2304C211720"."MENUS" 
   (	"NOMBRE" VARCHAR2(20 BYTE), 
	"COSTO_PRODUCCION" NUMBER, 
	"PRECIO_VENTA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table MESAS
--------------------------------------------------------

  CREATE TABLE "ISIS2304C211720"."MESAS" 
   (	"ID" NUMBER, 
	"ID_CLIENTE" NUMBER, 
	"ID_PEDIDO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table PEDIDOS
--------------------------------------------------------

  CREATE TABLE "ISIS2304C211720"."PEDIDOS" 
   (	"ID" NUMBER, 
	"FECHA" DATE, 
	"HORA" NUMBER, 
	"ACEPTADO" NUMBER, 
	"NOMBRE_USUARIO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table PREFERENCIAS
--------------------------------------------------------

  CREATE TABLE "ISIS2304C211720"."PREFERENCIAS" 
   (	"ID" NUMBER, 
	"PRECIO" NUMBER, 
	"ZONA" VARCHAR2(20 BYTE), 
	"TIPO_COMIDA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table PRODUCTO_INGREDIENTE
--------------------------------------------------------

  CREATE TABLE "ISIS2304C211720"."PRODUCTO_INGREDIENTE" 
   (	"NOMBRE_PRODUCTO" VARCHAR2(20 BYTE), 
	"NOMBRE_INGREDIENTE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table PRODUCTO_PEDIDO
--------------------------------------------------------

  CREATE TABLE "ISIS2304C211720"."PRODUCTO_PEDIDO" 
   (	"NOMBRE_PRODUCTO" VARCHAR2(20 BYTE), 
	"ID_PEDIDO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table PRODUCTOS
--------------------------------------------------------

  CREATE TABLE "ISIS2304C211720"."PRODUCTOS" 
   (	"NOMBRE" VARCHAR2(20 BYTE), 
	"DESCRIPCION" VARCHAR2(50 BYTE), 
	"TRADUCCION" VARCHAR2(50 BYTE), 
	"COSTO_PRODUCCION" NUMBER, 
	"PRECIO_VENTA" NUMBER, 
	"TIEMPO_PREPARACION" NUMBER, 
	"TIPO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table RESTAURANTE_MENU
--------------------------------------------------------

  CREATE TABLE "ISIS2304C211720"."RESTAURANTE_MENU" 
   (	"REPRESENTANTE_RESTAURANTE" VARCHAR2(20 BYTE), 
	"NOMBRE_MENU" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table RESTAURANTE_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "ISIS2304C211720"."RESTAURANTE_PRODUCTO" 
   (	"REPRESENTANTE_RESTAURANTE" VARCHAR2(50 BYTE), 
	"NOMBRE_PRODUCTO" VARCHAR2(50 BYTE), 
	"CANTIDAD_MAXIMA" NUMBER, 
	"CANTIDAD_ACTUAL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table RESTAURANTES
--------------------------------------------------------

  CREATE TABLE "ISIS2304C211720"."RESTAURANTES" 
   (	"REPRESENTANTE" VARCHAR2(50 BYTE), 
	"TIPO_COMIDA" VARCHAR2(50 BYTE), 
	"PAGINA_WEB" VARCHAR2(50 BYTE), 
	"NOMBRE_USUARIO" VARCHAR2(50 BYTE), 
	"ESTADO" VARCHAR2(20 BYTE) DEFAULT 'Activo'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table RESTAURANTE_ZONA
--------------------------------------------------------

  CREATE TABLE "ISIS2304C211720"."RESTAURANTE_ZONA" 
   (	"REPRESENTANTE_RESTAURANTE" VARCHAR2(20 BYTE), 
	"NOMBRE_ZONA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table SERVICIOS
--------------------------------------------------------

  CREATE TABLE "ISIS2304C211720"."SERVICIOS" 
   (	"ID_PEDIDO" NUMBER, 
	"NOMBRE_USUARIO" VARCHAR2(20 BYTE), 
	"REPRESENTANTE_RESTAURANTE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table TIPO_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "ISIS2304C211720"."TIPO_PRODUCTO" 
   (	"NOMBRE" VARCHAR2(20 BYTE), 
	"TIPO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "ISIS2304C211720"."USUARIOS" 
   (	"NOMBRE" VARCHAR2(20 BYTE), 
	"IDENTIFICACION" NUMBER, 
	"ROL" VARCHAR2(20 BYTE), 
	"CORREO_ELECTRONICO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table VIDEOS
--------------------------------------------------------

  CREATE TABLE "ISIS2304C211720"."VIDEOS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(255 BYTE), 
	"DURATION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Table ZONAS
--------------------------------------------------------

  CREATE TABLE "ISIS2304C211720"."ZONAS" 
   (	"NOMBRE" VARCHAR2(20 BYTE), 
	"ESPACIO_ABIERTO" NUMBER, 
	"CAPACIDAD" NUMBER, 
	"APTO_DISCAPACITADOS" VARCHAR2(20 BYTE), 
	"DESCRIPCION" VARCHAR2(20 BYTE), 
	"ESPECIALIZACION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index PRODUCTO_PEDIDO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304C211720"."PRODUCTO_PEDIDO_PK" ON "ISIS2304C211720"."PRODUCTO_PEDIDO" ("NOMBRE_PRODUCTO", "ID_PEDIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index PRODUCTO_INGREDIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304C211720"."PRODUCTO_INGREDIENTE_PK" ON "ISIS2304C211720"."PRODUCTO_INGREDIENTE" ("NOMBRE_PRODUCTO", "NOMBRE_INGREDIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index VIDEOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304C211720"."VIDEOS_PK" ON "ISIS2304C211720"."VIDEOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index EQUIVALENCIAS_INGREDIENTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304C211720"."EQUIVALENCIAS_INGREDIENTES_PK" ON "ISIS2304C211720"."EQUIVALENCIAS" ("NOMBRE1") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index RESTAURANTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304C211720"."RESTAURANTE_PK" ON "ISIS2304C211720"."RESTAURANTES" ("REPRESENTANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index CLIENTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304C211720"."CLIENTES_PK" ON "ISIS2304C211720"."CLIENTES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index ALQUILERES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304C211720"."ALQUILERES_PK" ON "ISIS2304C211720"."ALQUILERES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index RESTAURANTE_MENU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304C211720"."RESTAURANTE_MENU_PK" ON "ISIS2304C211720"."RESTAURANTE_MENU" ("REPRESENTANTE_RESTAURANTE", "NOMBRE_MENU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index SERVIVIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304C211720"."SERVIVIOS_PK" ON "ISIS2304C211720"."SERVICIOS" ("ID_PEDIDO", "NOMBRE_USUARIO", "REPRESENTANTE_RESTAURANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index INDICE_PRODIDPED
--------------------------------------------------------

  CREATE INDEX "ISIS2304C211720"."INDICE_PRODIDPED" ON "ISIS2304C211720"."PRODUCTO_PEDIDO" ("ID_PEDIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index TIPOCOMIDA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304C211720"."TIPOCOMIDA_PK" ON "ISIS2304C211720"."TIPO_PRODUCTO" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index INGREDIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304C211720"."INGREDIENTE_PK" ON "ISIS2304C211720"."INGREDIENTES" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index RESTAURANTE_PRODUCTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304C211720"."RESTAURANTE_PRODUCTO_PK" ON "ISIS2304C211720"."RESTAURANTE_PRODUCTO" ("REPRESENTANTE_RESTAURANTE", "NOMBRE_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index USUARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304C211720"."USUARIOS_PK" ON "ISIS2304C211720"."USUARIOS" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index PREFERENCIAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304C211720"."PREFERENCIAS_PK" ON "ISIS2304C211720"."PREFERENCIAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index MENUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304C211720"."MENUS_PK" ON "ISIS2304C211720"."MENUS" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index PEDIDOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304C211720"."PEDIDOS_PK" ON "ISIS2304C211720"."PEDIDOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index INDICE_ROL
--------------------------------------------------------

  CREATE BITMAP INDEX "ISIS2304C211720"."INDICE_ROL" ON "ISIS2304C211720"."USUARIOS" ("ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index MENU_PRODUCTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304C211720"."MENU_PRODUCTO_PK" ON "ISIS2304C211720"."MENU_PRODUCTO" ("NOMBRE_MENU", "NOMBRE_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index MESAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304C211720"."MESAS_PK" ON "ISIS2304C211720"."MESAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304C211720"."TABLE1_PK" ON "ISIS2304C211720"."PRODUCTOS" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index RESTAURANTE_ZONA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304C211720"."RESTAURANTE_ZONA_PK" ON "ISIS2304C211720"."RESTAURANTE_ZONA" ("REPRESENTANTE_RESTAURANTE", "NOMBRE_ZONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  DDL for Index ZONAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISIS2304C211720"."ZONAS_PK" ON "ISIS2304C211720"."ZONAS" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD" ;
--------------------------------------------------------
--  Constraints for Table SERVICIOS
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."SERVICIOS" MODIFY ("ID_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."SERVICIOS" MODIFY ("NOMBRE_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."SERVICIOS" MODIFY ("REPRESENTANTE_RESTAURANTE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."SERVICIOS" ADD CONSTRAINT "SERVIVIOS_PK" PRIMARY KEY ("ID_PEDIDO", "NOMBRE_USUARIO", "REPRESENTANTE_RESTAURANTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTO_INGREDIENTE
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."PRODUCTO_INGREDIENTE" MODIFY ("NOMBRE_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."PRODUCTO_INGREDIENTE" MODIFY ("NOMBRE_INGREDIENTE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."PRODUCTO_INGREDIENTE" ADD CONSTRAINT "PRODUCTO_INGREDIENTE_PK" PRIMARY KEY ("NOMBRE_PRODUCTO", "NOMBRE_INGREDIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESTAURANTES
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."RESTAURANTES" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."RESTAURANTES" ADD CONSTRAINT "RESTAURANTE_PK" PRIMARY KEY ("REPRESENTANTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304C211720"."RESTAURANTES" MODIFY ("NOMBRE_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."RESTAURANTES" MODIFY ("REPRESENTANTE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."RESTAURANTES" MODIFY ("TIPO_COMIDA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ZONAS
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."ZONAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."ZONAS" ADD CONSTRAINT "ZONAS_PK" PRIMARY KEY ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304C211720"."ZONAS" MODIFY ("ESPACIO_ABIERTO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."ZONAS" MODIFY ("CAPACIDAD" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."ZONAS" MODIFY ("APTO_DISCAPACITADOS" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."ZONAS" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."ZONAS" MODIFY ("ESPECIALIZACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIVALENCIAS
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."EQUIVALENCIAS" MODIFY ("NOMBRE1" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."EQUIVALENCIAS" MODIFY ("NOMBRE2" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."EQUIVALENCIAS" ADD CONSTRAINT "EQUIVALENCIAS_INGREDIENTES_PK" PRIMARY KEY ("NOMBRE1")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304C211720"."EQUIVALENCIAS" MODIFY ("TIPO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESTAURANTE_ZONA
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."RESTAURANTE_ZONA" ADD CONSTRAINT "RESTAURANTE_ZONA_PK" PRIMARY KEY ("REPRESENTANTE_RESTAURANTE", "NOMBRE_ZONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304C211720"."RESTAURANTE_ZONA" MODIFY ("NOMBRE_ZONA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."RESTAURANTE_ZONA" MODIFY ("REPRESENTANTE_RESTAURANTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PREFERENCIAS
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."PREFERENCIAS" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."PREFERENCIAS" MODIFY ("ZONA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."PREFERENCIAS" MODIFY ("TIPO_COMIDA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."PREFERENCIAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."PREFERENCIAS" ADD CONSTRAINT "PREFERENCIAS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PEDIDOS
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."PEDIDOS" MODIFY ("NOMBRE_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."PEDIDOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."PEDIDOS" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."PEDIDOS" MODIFY ("HORA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."PEDIDOS" MODIFY ("ACEPTADO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."PEDIDOS" ADD CONSTRAINT "PEDIDOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INGREDIENTES
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."INGREDIENTES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."INGREDIENTES" ADD CONSTRAINT "INGREDIENTE_PK" PRIMARY KEY ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304C211720"."INGREDIENTES" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."INGREDIENTES" MODIFY ("TRADUCCION" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."INGREDIENTES" MODIFY ("CANTIDAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCTO_PEDIDO
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."PRODUCTO_PEDIDO" MODIFY ("NOMBRE_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."PRODUCTO_PEDIDO" MODIFY ("ID_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."PRODUCTO_PEDIDO" ADD CONSTRAINT "PRODUCTO_PEDIDO_PK" PRIMARY KEY ("NOMBRE_PRODUCTO", "ID_PEDIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTOS
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."PRODUCTOS" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."PRODUCTOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."PRODUCTOS" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304C211720"."PRODUCTOS" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."PRODUCTOS" MODIFY ("TRADUCCION" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."PRODUCTOS" MODIFY ("COSTO_PRODUCCION" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."PRODUCTOS" MODIFY ("PRECIO_VENTA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."PRODUCTOS" MODIFY ("TIEMPO_PREPARACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."USUARIOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."USUARIOS" ADD CONSTRAINT "USUARIOS_PK" PRIMARY KEY ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304C211720"."USUARIOS" MODIFY ("IDENTIFICACION" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."USUARIOS" MODIFY ("ROL" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."USUARIOS" MODIFY ("CORREO_ELECTRONICO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MESAS
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."MESAS" MODIFY ("ID_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."MESAS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."MESAS" ADD CONSTRAINT "MESAS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304C211720"."MESAS" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."TIPO_PRODUCTO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."TIPO_PRODUCTO" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."TIPO_PRODUCTO" ADD CONSTRAINT "TIPOCOMIDA_PK" PRIMARY KEY ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VIDEOS
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."VIDEOS" ADD CONSTRAINT "VIDEOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304C211720"."VIDEOS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."CLIENTES" MODIFY ("NOMBRE_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."CLIENTES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."CLIENTES" ADD CONSTRAINT "CLIENTES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MENU_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."MENU_PRODUCTO" MODIFY ("NOMBRE_MENU" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."MENU_PRODUCTO" MODIFY ("NOMBRE_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."MENU_PRODUCTO" ADD CONSTRAINT "MENU_PRODUCTO_PK" PRIMARY KEY ("NOMBRE_MENU", "NOMBRE_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MENUS
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."MENUS" MODIFY ("COSTO_PRODUCCION" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."MENUS" MODIFY ("PRECIO_VENTA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."MENUS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."MENUS" ADD CONSTRAINT "MENUS_PK" PRIMARY KEY ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESTAURANTE_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."RESTAURANTE_PRODUCTO" MODIFY ("REPRESENTANTE_RESTAURANTE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."RESTAURANTE_PRODUCTO" MODIFY ("NOMBRE_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."RESTAURANTE_PRODUCTO" ADD CONSTRAINT "RESTAURANTE_PRODUCTO_PK" PRIMARY KEY ("REPRESENTANTE_RESTAURANTE", "NOMBRE_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304C211720"."RESTAURANTE_PRODUCTO" MODIFY ("CANTIDAD_MAXIMA" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."RESTAURANTE_PRODUCTO" MODIFY ("CANTIDAD_ACTUAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ALQUILERES
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."ALQUILERES" ADD CONSTRAINT "ALQUILERES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPROD"  ENABLE;
  ALTER TABLE "ISIS2304C211720"."ALQUILERES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESTAURANTE_MENU
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."RESTAURANTE_MENU" MODIFY ("REPRESENTANTE_RESTAURANTE" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."RESTAURANTE_MENU" MODIFY ("NOMBRE_MENU" NOT NULL ENABLE);
  ALTER TABLE "ISIS2304C211720"."RESTAURANTE_MENU" ADD CONSTRAINT "RESTAURANTE_MENU_PK" PRIMARY KEY ("REPRESENTANTE_RESTAURANTE", "NOMBRE_MENU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "TBSPROD"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ALQUILERES
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."ALQUILERES" ADD CONSTRAINT "FK_VIDEO" FOREIGN KEY ("VIDEO_ID")
	  REFERENCES "ISIS2304C211720"."VIDEOS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."CLIENTES" ADD CONSTRAINT "CLIENTESPK" FOREIGN KEY ("NOMBRE_USUARIO")
	  REFERENCES "ISIS2304C211720"."USUARIOS" ("NOMBRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MENU_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."MENU_PRODUCTO" ADD CONSTRAINT "MENUNOMPK" FOREIGN KEY ("NOMBRE_PRODUCTO")
	  REFERENCES "ISIS2304C211720"."PRODUCTOS" ("NOMBRE") ENABLE;
  ALTER TABLE "ISIS2304C211720"."MENU_PRODUCTO" ADD CONSTRAINT "MENUPKK" FOREIGN KEY ("NOMBRE_MENU")
	  REFERENCES "ISIS2304C211720"."MENUS" ("NOMBRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MESAS
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."MESAS" ADD CONSTRAINT "CLIENTEMESA" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "ISIS2304C211720"."CLIENTES" ("ID") ENABLE;
  ALTER TABLE "ISIS2304C211720"."MESAS" ADD CONSTRAINT "PEDIDOMESA" FOREIGN KEY ("ID_PEDIDO")
	  REFERENCES "ISIS2304C211720"."PEDIDOS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PEDIDOS
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."PEDIDOS" ADD CONSTRAINT "PEDIDOUSUPK" FOREIGN KEY ("NOMBRE_USUARIO")
	  REFERENCES "ISIS2304C211720"."USUARIOS" ("NOMBRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTO_PEDIDO
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."PRODUCTO_PEDIDO" ADD CONSTRAINT "IDPEDPKA" FOREIGN KEY ("ID_PEDIDO")
	  REFERENCES "ISIS2304C211720"."PEDIDOS" ("ID") ENABLE;
  ALTER TABLE "ISIS2304C211720"."PRODUCTO_PEDIDO" ADD CONSTRAINT "NOMPPK" FOREIGN KEY ("NOMBRE_PRODUCTO")
	  REFERENCES "ISIS2304C211720"."PRODUCTOS" ("NOMBRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESTAURANTE_MENU
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."RESTAURANTE_MENU" ADD CONSTRAINT "RESTMENUPKA" FOREIGN KEY ("REPRESENTANTE_RESTAURANTE")
	  REFERENCES "ISIS2304C211720"."RESTAURANTES" ("REPRESENTANTE") ENABLE;
  ALTER TABLE "ISIS2304C211720"."RESTAURANTE_MENU" ADD CONSTRAINT "RESTMENUPKB" FOREIGN KEY ("NOMBRE_MENU")
	  REFERENCES "ISIS2304C211720"."MENUS" ("NOMBRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESTAURANTE_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."RESTAURANTE_PRODUCTO" ADD CONSTRAINT "RPPK1" FOREIGN KEY ("REPRESENTANTE_RESTAURANTE")
	  REFERENCES "ISIS2304C211720"."RESTAURANTES" ("REPRESENTANTE") ENABLE;
  ALTER TABLE "ISIS2304C211720"."RESTAURANTE_PRODUCTO" ADD CONSTRAINT "RPPK2" FOREIGN KEY ("NOMBRE_PRODUCTO")
	  REFERENCES "ISIS2304C211720"."PRODUCTOS" ("NOMBRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESTAURANTES
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."RESTAURANTES" ADD CONSTRAINT "RESTPK" FOREIGN KEY ("NOMBRE_USUARIO")
	  REFERENCES "ISIS2304C211720"."USUARIOS" ("NOMBRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESTAURANTE_ZONA
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."RESTAURANTE_ZONA" ADD CONSTRAINT "RESTZONA" FOREIGN KEY ("REPRESENTANTE_RESTAURANTE")
	  REFERENCES "ISIS2304C211720"."RESTAURANTES" ("REPRESENTANTE") ENABLE;
  ALTER TABLE "ISIS2304C211720"."RESTAURANTE_ZONA" ADD CONSTRAINT "ZONAREST" FOREIGN KEY ("NOMBRE_ZONA")
	  REFERENCES "ISIS2304C211720"."ZONAS" ("NOMBRE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SERVICIOS
--------------------------------------------------------

  ALTER TABLE "ISIS2304C211720"."SERVICIOS" ADD CONSTRAINT "SERVICIOSIDPK" FOREIGN KEY ("ID_PEDIDO")
	  REFERENCES "ISIS2304C211720"."PEDIDOS" ("ID") ENABLE;
  ALTER TABLE "ISIS2304C211720"."SERVICIOS" ADD CONSTRAINT "SERVICIOSNOMPK" FOREIGN KEY ("NOMBRE_USUARIO")
	  REFERENCES "ISIS2304C211720"."USUARIOS" ("NOMBRE") ENABLE;
  ALTER TABLE "ISIS2304C211720"."SERVICIOS" ADD CONSTRAINT "SERVICIOSREP" FOREIGN KEY ("REPRESENTANTE_RESTAURANTE")
	  REFERENCES "ISIS2304C211720"."RESTAURANTES" ("REPRESENTANTE") ENABLE;
